import Head from "next/head";
import React from "react";
import Navbar from "@/components/Navbar";

const Layout = ({ title, children }) => {
  return (
    <div>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/pokeball.png" />
      </Head>
      <Navbar />
      <div className="bg-gray-300 min-h-screen">{children}</div>
    </div>
  );
};

export default Layout;
